# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\" \n\x0bJoinRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\"0\n\x0cJoinResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x0cLeaveRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\"1\n\rLeaveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"N\n\rUpdateRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x17\n\x08position\x18\x02 \x01(\x0b\x32\x05.Vec2\x12\x11\n\tdirection\x18\x03 \x01(\x02\"\x1c\n\x04Vec2\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"L\n\x0bPlayerState\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x17\n\x08position\x18\x02 \x01(\x0b\x32\x05.Vec2\x12\x11\n\tdirection\x18\x03 \x01(\x02\"`\n\x06\x42ullet\x12\x10\n\x08owner_id\x18\x01 \x01(\t\x12\x11\n\tbullet_id\x18\x02 \x01(\x05\x12\x17\n\x08position\x18\x03 \x01(\x0b\x32\x05.Vec2\x12\x18\n\tdirection\x18\x04 \x01(\x0b\x32\x05.Vec2\"H\n\x0eUpdateResponse\x12\x1c\n\x06states\x18\x01 \x03(\x0b\x32\x0c.PlayerState\x12\x18\n\x07\x62ullets\x18\x02 \x03(\x0b\x32\x07.Bullet\"!\n\x0cShootRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\" \n\rShootResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa6\x01\n\x04Game\x12#\n\x04Join\x12\x0c.JoinRequest\x1a\r.JoinResponse\x12&\n\x05Leave\x12\r.LeaveRequest\x1a\x0e.LeaveResponse\x12)\n\x06Update\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\x12&\n\x05Shoot\x12\r.ShootRequest\x1a\x0e.ShootResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINREQUEST']._serialized_start=14
  _globals['_JOINREQUEST']._serialized_end=46
  _globals['_JOINRESPONSE']._serialized_start=48
  _globals['_JOINRESPONSE']._serialized_end=96
  _globals['_LEAVEREQUEST']._serialized_start=98
  _globals['_LEAVEREQUEST']._serialized_end=131
  _globals['_LEAVERESPONSE']._serialized_start=133
  _globals['_LEAVERESPONSE']._serialized_end=182
  _globals['_UPDATEREQUEST']._serialized_start=184
  _globals['_UPDATEREQUEST']._serialized_end=262
  _globals['_VEC2']._serialized_start=264
  _globals['_VEC2']._serialized_end=292
  _globals['_PLAYERSTATE']._serialized_start=294
  _globals['_PLAYERSTATE']._serialized_end=370
  _globals['_BULLET']._serialized_start=372
  _globals['_BULLET']._serialized_end=468
  _globals['_UPDATERESPONSE']._serialized_start=470
  _globals['_UPDATERESPONSE']._serialized_end=542
  _globals['_SHOOTREQUEST']._serialized_start=544
  _globals['_SHOOTREQUEST']._serialized_end=577
  _globals['_SHOOTRESPONSE']._serialized_start=579
  _globals['_SHOOTRESPONSE']._serialized_end=611
  _globals['_GAME']._serialized_start=614
  _globals['_GAME']._serialized_end=780
# @@protoc_insertion_point(module_scope)
